"""CLIP-ReID pipeline — orchestrates the official two-stage trainer.

Training is delegated to the official CLIP-ReID codebase (Syliz517/CLIP-ReID,
MIT — expected as a checkout under ``third_party/CLIP-ReID``; see
:data:`CLIPREID_DIR`). Re-implementing its two-stage recipe (stage 1 learns
identity prompts, stage 2 fine-tunes the image encoder with ID + triplet +
image-to-text losses) is not worth the drift risk, so this module instead:

  1. generates a yacs config matching the DEPLOYED encoder architecture
     (ViT-B/16, overlapping patches stride 12, SIE camera embeddings, 256x128 —
     the ``12x12sie`` family consumed by TRACE's ``piaspace_clip_reid``);
  2. generates a small launcher that registers our Market-1501-layout dataset
     in the official ``__factory`` (their ``Market1501`` class hard-asserts
     ``pid <= 1501`` / ``camid <= 6``, so it cannot ingest MTMDC's 16 cameras)
     and then executes their unmodified ``train_clipreid.py`` via ``runpy``;
  3. runs the launcher as a subprocess (their top-level module names —
     ``config``, ``datasets``, ``model`` — are too generic to import in-process
     safely).

The resulting ``ViT-B-16_<epoch>.pth`` is the exact format TRACE consumes
(``piaspace_clip_reid`` strips ``image_encoder.``/keeps ``bottleneck.*``), and
converts to a TRT engine with the existing
``scripts/conversion/convert_clipreid_to_trt.sh person --weights <pth>``.

Evaluation deliberately embeds through the DEPLOYED ``piaspace_clip_reid``
encoder (PyTorch path) rather than the training code — every eval is thereby
also a deployment-contract test.
"""

from __future__ import annotations

import logging
import os
import subprocess
import sys
from pathlib import Path
from typing import Any

import numpy as np
import yaml

from basicdet.metrics.reid import evaluate_retrieval
from basicdet.models.reid_data import ReIDSplit, load_market_dataset
from basicdet.utils.config import ClipReIDExperimentConfig
from basicdet.utils.runtime import resolve_torch_device

logger = logging.getLogger(__name__)

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
CLIPREID_DIR = _REPO_ROOT / "third_party" / "CLIP-ReID"
PINNED_COMMIT = "eb1898b72c882875f478bebfc6d41644eece0a5d"
RUNS_DIR = Path("runs/reid")

# Runs inside third_party/CLIP-ReID: registers the persondet dataset in the
# official factory, then executes their train_clipreid.py unmodified.
_LAUNCHER_TEMPLATE = '''"""Auto-generated by basicdet.models.reid_clipreid — do not edit."""
import glob
import os.path as osp
import re
import runpy
import sys

from datasets import make_dataloader_clipreid as _mdl
from datasets.bases import BaseImageDataset

_NAME_RE = re.compile(r"^(-?\\d+)_c(\\d+)")


class PersondetReID(BaseImageDataset):
    """Market-1501-layout dataset without Market's pid/camid range asserts."""

    def __init__(self, root="", verbose=True, **kwargs):
        super().__init__()
        self.dataset_dir = root
        train, cam_map = self._scan(osp.join(root, "bounding_box_train"), relabel=True)
        query, _ = self._scan(osp.join(root, "query"), relabel=False, cam_map=cam_map)
        gallery, _ = self._scan(
            osp.join(root, "bounding_box_test"), relabel=False, cam_map=cam_map
        )
        self.train, self.query, self.gallery = train, query, gallery
        (self.num_train_pids, self.num_train_imgs, self.num_train_cams,
         self.num_train_vids) = self.get_imagedata_info(train)
        (self.num_query_pids, self.num_query_imgs, self.num_query_cams,
         self.num_query_vids) = self.get_imagedata_info(query)
        (self.num_gallery_pids, self.num_gallery_imgs, self.num_gallery_cams,
         self.num_gallery_vids) = self.get_imagedata_info(gallery)
        if verbose:
            print("=> persondet ReID loaded")
            self.print_dataset_statistics(train, query, gallery)

    def _scan(self, split_dir, relabel, cam_map=None):
        paths = sorted(glob.glob(osp.join(split_dir, "*.jpg")))
        paths += sorted(glob.glob(osp.join(split_dir, "*.png")))
        raw = []
        for p in paths:
            m = _NAME_RE.match(osp.basename(p))
            if m is None:
                raise ValueError("not a Market-style name: " + p)
            raw.append((p, int(m.group(1)), int(m.group(2))))
        raw = [(p, pid, cam) for p, pid, cam in raw if not (relabel and pid == -1)]
        if cam_map is None:
            cam_map = {c: i for i, c in enumerate(sorted({cam for _, _, cam in raw}))}
        pid_map = {pid: i for i, pid in enumerate(sorted({pid for _, pid, _ in raw}))}
        out = []
        for p, pid, cam in raw:
            label = pid_map[pid] if relabel else pid
            out.append((p, label, cam_map.get(cam, len(cam_map)), 0))
        return out, cam_map


_mdl.__factory["persondet"] = PersondetReID

# Warm-start from an existing CLIP-ReID checkpoint. The official trainer never
# calls load_param, so wrap make_model instead: train_clipreid does
# `from model.make_model_clipreid import make_model` at its own import time,
# which happens inside runpy below — so patching the module attribute now is
# picked up. Identity- and camera-sized tensors (classifier, classifier_proj,
# prompt_learner.cls_ctx, cv_embed) cannot transfer to a dataset with a
# different identity/camera count, so they are skipped on shape mismatch and
# stay randomly initialised.
__WARM_START__


sys.argv = ["train_clipreid.py", "--config_file", __CONFIG_FILE__] + __OPTS__
runpy.run_path("train_clipreid.py", run_name="__main__")
'''

_WARM_START_TEMPLATE = """import torch
import model.make_model_clipreid as _mm

_WEIGHTS = __WEIGHTS__
_orig_make_model = _mm.make_model


def _load_transferable(net, path):
    sd = torch.load(path, map_location="cpu", weights_only=False)
    if isinstance(sd, dict) and "state_dict" in sd:
        sd = sd["state_dict"]
    own = net.state_dict()
    loaded, skipped = [], []
    for k, v in sd.items():
        key = k.replace("module.", "")
        if key in own and own[key].shape == v.shape:
            own[key].copy_(v)
            loaded.append(key)
        else:
            skipped.append(key)
    print("[warm-start] loaded {}/{} tensors from {}".format(len(loaded), len(sd), path))
    print("[warm-start] skipped (shape mismatch or absent): {}".format(sorted(skipped)))
    if not loaded:
        raise RuntimeError("warm-start loaded 0 tensors — wrong checkpoint for this architecture?")


def _make_model_warm(cfg, num_class, camera_num, view_num):
    net = _orig_make_model(cfg, num_class=num_class, camera_num=camera_num, view_num=view_num)
    _load_transferable(net, _WEIGHTS)
    return net


_mm.make_model = _make_model_warm
"""


def _require_checkout() -> None:
    """Fail loudly (with the fix) when the official checkout is absent."""
    if not (CLIPREID_DIR / "train_clipreid.py").is_file():
        raise FileNotFoundError(
            f"CLIP-ReID checkout not found at {CLIPREID_DIR}. Clone it with:\n"
            f"  git clone https://github.com/Syliz517/CLIP-ReID.git {CLIPREID_DIR}\n"
            f"(pinned commit {PINNED_COMMIT})"
        )
    head = subprocess.run(
        ["git", "-C", str(CLIPREID_DIR), "rev-parse", "HEAD"],
        capture_output=True,
        text=True,
        check=False,
    ).stdout.strip()
    if head and head != PINNED_COMMIT:
        logger.warning("CLIP-ReID checkout at %s, expected %s", head[:12], PINNED_COMMIT[:12])


def _official_config(config: ClipReIDExperimentConfig, output_dir: Path) -> dict[str, Any]:
    """The official person recipe with the deployed-architecture overrides."""
    h, w = config.model.input_size
    return {
        "MODEL": {
            "PRETRAIN_CHOICE": "imagenet",
            "METRIC_LOSS_TYPE": "triplet",
            "IF_LABELSMOOTH": "on",
            "IF_WITH_CENTER": "no",
            "NAME": config.model.backbone,
            # Deployed "12x12sie" architecture: overlapping patches + SIE.
            "STRIDE_SIZE": [config.model.stride, config.model.stride],
            "SIE_CAMERA": config.model.sie_camera,
            "SIE_COE": 1.0,
            "ID_LOSS_WEIGHT": 0.25,
            "TRIPLET_LOSS_WEIGHT": 1.0,
            "I2T_LOSS_WEIGHT": 1.0,
        },
        "INPUT": {
            "SIZE_TRAIN": [h, w],
            "SIZE_TEST": [h, w],
            "PROB": 0.5,
            "RE_PROB": 0.5,
            "PADDING": 10,
            "PIXEL_MEAN": [0.5, 0.5, 0.5],
            "PIXEL_STD": [0.5, 0.5, 0.5],
        },
        "DATALOADER": {
            "SAMPLER": "softmax_triplet",
            "NUM_INSTANCE": config.train.num_instances,
            "NUM_WORKERS": config.train.workers,
        },
        "SOLVER": {
            "SEED": config.train.seed,
            "STAGE1": {
                "IMS_PER_BATCH": 64,
                "OPTIMIZER_NAME": "Adam",
                "BASE_LR": 0.00035,
                "WARMUP_LR_INIT": 0.00001,
                "LR_MIN": 1e-6,
                "WARMUP_METHOD": "linear",
                "WEIGHT_DECAY": 1e-4,
                "WEIGHT_DECAY_BIAS": 1e-4,
                "MAX_EPOCHS": config.train.stage1_epochs,
                "CHECKPOINT_PERIOD": config.train.stage1_epochs,
                "LOG_PERIOD": 50,
                "WARMUP_EPOCHS": 5,
            },
            "STAGE2": {
                "IMS_PER_BATCH": config.train.batch,
                "OPTIMIZER_NAME": "Adam",
                "BASE_LR": config.train.base_lr_stage2,
                "WARMUP_METHOD": "linear",
                "WARMUP_ITERS": 10,
                "WARMUP_FACTOR": 0.1,
                "WEIGHT_DECAY": 1e-4,
                "WEIGHT_DECAY_BIAS": 1e-4,
                "LARGE_FC_LR": False,
                "MAX_EPOCHS": config.train.stage2_epochs,
                "CHECKPOINT_PERIOD": config.train.stage2_epochs,
                "LOG_PERIOD": 50,
                "EVAL_PERIOD": config.train.stage2_epochs,
                "BIAS_LR_FACTOR": 2,
                "STEPS": [30, 50],
                "GAMMA": 0.1,
            },
        },
        "TEST": {
            "EVAL": True,
            "IMS_PER_BATCH": 64,
            "RE_RANKING": False,
            "WEIGHT": "",
            "NECK_FEAT": "before",
            "FEAT_NORM": "yes",
        },
        "DATASETS": {
            "NAMES": "persondet",
            "ROOT_DIR": str(Path(config.data.dataset_dir).resolve()),
        },
        "OUTPUT_DIR": str(output_dir.resolve()),
    }


def train(config: ClipReIDExperimentConfig) -> Path:
    """Run the official two-stage CLIP-ReID fine-tune on our dataset.

    Args:
        config: The validated experiment configuration.

    Returns:
        Path to the final checkpoint
        (``runs/reid/<name>/<backbone>_<stage2_epochs>.pth``) — directly
        consumable by TRACE's ``piaspace_clip_reid`` and the TRT converter.

    Raises:
        FileNotFoundError: If the third_party checkout, dataset, or
            ``train.pretrain_weights`` checkpoint is missing.
        RuntimeError: If the subprocess exits non-zero.
    """
    _require_checkout()
    warm = config.train.pretrain_weights
    if warm is not None and not Path(warm).is_file():
        raise FileNotFoundError(f"pretrain_weights checkpoint not found: {warm}")
    load_market_dataset(config.data.dataset_dir)  # fail fast on layout problems

    out_dir = (RUNS_DIR / config.train.name).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    cfg_path = out_dir / "official_config.yml"
    cfg_path.write_text(yaml.safe_dump(_official_config(config, out_dir), sort_keys=False))

    opts = [str(x) for kv in config.train.extra.items() for x in kv]
    launcher = out_dir / "launcher.py"
    warm_block = (
        _WARM_START_TEMPLATE.replace("__WEIGHTS__", repr(str(Path(warm).resolve())))
        if warm is not None
        else ""
    )
    launcher_code = (
        _LAUNCHER_TEMPLATE.replace("__CONFIG_FILE__", repr(str(cfg_path)))
        .replace("__OPTS__", repr(opts))
        .replace("__WARM_START__", warm_block)
    )
    launcher.write_text(launcher_code)
    if warm is not None:
        logger.info("warm-starting from %s (identity/camera tensors will be skipped)", warm)

    env = dict(os.environ)
    # The launcher runs by absolute path, so cwd is not on sys.path — the
    # official repo's top-level modules (datasets/, model/, ...) need this.
    env["PYTHONPATH"] = str(CLIPREID_DIR) + os.pathsep + env.get("PYTHONPATH", "")
    if config.train.device not in ("auto", "cpu"):
        env["CUDA_VISIBLE_DEVICES"] = config.train.device.removeprefix("cuda:")
    log_path = out_dir / "train.log"
    logger.info("CLIP-ReID two-stage train -> %s (log: %s)", out_dir, log_path)
    with open(log_path, "w", encoding="utf-8") as log_fh:
        result = subprocess.run(
            [sys.executable, str(launcher)],
            cwd=CLIPREID_DIR,
            env=env,
            stdout=log_fh,
            stderr=subprocess.STDOUT,
            check=False,
        )
    if result.returncode != 0:
        raise RuntimeError(f"CLIP-ReID training failed (exit {result.returncode}) — see {log_path}")
    ckpt = out_dir / f"{config.model.backbone}_{config.train.stage2_epochs}.pth"
    logger.info(
        "CLIP-ReID checkpoint: %s (TRACE-ready; convert via "
        "convert_clipreid_to_trt.sh person --weights <path>)",
        ckpt,
    )
    return ckpt


def _deployed_embedder(config: ClipReIDExperimentConfig, weights: str) -> Any:
    """Instantiate TRACE's ``piaspace_clip_reid`` embedder (PyTorch path)."""
    pkg = Path(config.train.piaspace_pkg)
    if not (pkg / "piaspace_clip_reid").is_dir():
        raise FileNotFoundError(
            f"piaspace_clip_reid not found under {pkg} — set train.piaspace_pkg to "
            "<TRACE repo>/packages/piaspace-clip-reid/src"
        )
    if str(pkg) not in sys.path:
        sys.path.insert(0, str(pkg))
    from piaspace_clip_reid import CLIPReIDEmbedder

    return CLIPReIDEmbedder(
        {
            "device": resolve_torch_device(config.train.device),
            "input_size": list(config.model.input_size),
            "stride": config.model.stride,
            "weights_path": weights,
        }
    )


def _embed_split(embedder: Any, split: ReIDSplit, batch: int = 64) -> np.ndarray:
    import cv2

    feats: list[np.ndarray] = []
    for i in range(0, len(split.paths), batch):
        crops = [cv2.imread(str(p)) for p in split.paths[i : i + batch]]
        feats.append(embedder.embed(crops))
    return np.concatenate(feats, axis=0)


def evaluate(
    config: ClipReIDExperimentConfig,
    weights: str,
    split: str = "test",
    conf: float | None = None,
) -> dict[str, float]:
    """mAP / CMC on query-gallery, embedded through the DEPLOYED encoder.

    Using ``piaspace_clip_reid`` (not the training code) makes every eval a
    deployment-contract test: if the checkpoint fails to load or embeds
    garbage here, it would do the same inside TRACE.

    Args:
        config: The experiment configuration.
        weights: Path to a CLIP-ReID ``.pth`` checkpoint.
        split: Accepted for registry-signature compatibility (unused).
        conf: Unused for ReID (registry-signature compatibility).

    Returns:
        ``{"mAP": ..., "rank1": ..., ...}``.
    """
    del split, conf
    # Evaluation-only sets (e.g. pia_aihub4_v1) ship an empty train split by
    # design; only query/gallery are read below.
    data = load_market_dataset(config.data.dataset_dir, require_train=False)
    embedder = _deployed_embedder(config, weights)
    q = _embed_split(embedder, data.query)
    g = _embed_split(embedder, data.gallery)
    return evaluate_retrieval(
        q, data.query.pids, data.query.camids, g, data.gallery.pids, data.gallery.camids
    )


def predict(
    config: ClipReIDExperimentConfig,
    weights: str,
    source: Path,
    output: Path,
    conf: float = 0.25,
) -> Any:
    """Embed every crop under ``source`` with the deployed encoder.

    Args:
        config: The experiment configuration.
        weights: Path to a CLIP-ReID ``.pth`` checkpoint.
        source: Directory of person crops.
        output: Output directory for ``features.npy`` + ``index.csv``.
        conf: Unused for ReID (registry-signature compatibility).

    Returns:
        The ``[N, dim]`` feature matrix.
    """
    del conf
    paths = sorted(Path(source).glob("*.jpg")) + sorted(Path(source).glob("*.png"))
    split = ReIDSplit(paths, np.zeros(len(paths), np.int64), np.zeros(len(paths), np.int64))
    embedder = _deployed_embedder(config, weights)
    feats = _embed_split(embedder, split)
    output = Path(output)
    output.mkdir(parents=True, exist_ok=True)
    np.save(output / "features.npy", feats)
    (output / "index.csv").write_text("\n".join(str(p) for p in paths) + "\n")
    logger.info("embedded %d crops -> %s", len(paths), output)
    return feats
